### PR TITLE
Added the libraries

### PR DESCRIPTION
**Pull request by Chana-C**
I checked in thr main branch and there is no library openzepplin.
I installed it and pushed it.
So that the library to be in the main branch, you need to perform a merge with this branch.

I did it in this branch altouth it is not match to the topic.

### CODE REVIEW

**Review by YehudisSternberg — CHANGES_REQUESTED** [review]
can you please fix the connflict

**Comment by YehudisSternberg** [comment]
why do you have so much files chaned

**Comment by Chana-C** [comment]
This is cairo 0 and to this project we need cairo 1.
The openzepplin does not meach.

**Comment by henry-hz** [comment]
pls fix the PR, you have tons of libs, 1567 files

**Comment by HadasaHazan** [comment]
chane you added 1565 files in this PR, Do you need all of them, check it again.

**Comment by Chana-C** [comment]
I do not need it.
Henry said to check if the openzeplin exists in MAIN
I saw he wasn't so I added.
But this is version 0.

**Pull request closed without merging**
